version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=345Adf45LT3.0
      - POSTGRES_DB=lineupdb 
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./liquid.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
volumes:
  postgres_data:

    