-- Table: public.lineups

-- DROP TABLE IF EXISTS public.lineups;

CREATE TABLE IF NOT EXISTS public.lineups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    agent character varying(30) COLLATE pg_catalog."default" NOT NULL,
    mapname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    objective character varying(10) COLLATE pg_catalog."default" NOT NULL,
    ability character varying(45) COLLATE pg_catalog."default" NOT NULL,
    source character varying(80) COLLATE pg_catalog."default" NOT NULL,
    author integer,
    CONSTRAINT lineups_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.lineups
    OWNER to postgres;


-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(500) COLLATE pg_catalog."default" NOT NULL,
    role character varying(45) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

-- SEQUENCE: public.lineups_id_seq

-- DROP SEQUENCE IF EXISTS public.lineups_id_seq;

CREATE SEQUENCE IF NOT EXISTS public.lineups_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.lineups_id_seq
    OWNER TO postgres;

-- SEQUENCE: public.users_id_seq

-- DROP SEQUENCE IF EXISTS public.users_id_seq;

CREATE SEQUENCE IF NOT EXISTS public.users_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

ALTER SEQUENCE public.users_id_seq
    OWNER TO postgres;